name: 'AWS cli install'
description: 'Sets up AWS CLI Credentials on Ubuntu 20.04'
author: 'george.p@wealthberry.com'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  aws_access_key_id:
    description: 'AWS Account Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  region:
    description: 'Default region to set to AWS cli'
    required: false
    default: us-east-1
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/awscli_setup.sh ${{ inputs.region }} ${{ inputs.aws_access_key_id }} ${{ inputs.aws_secret_access_key }}
      shell: bash
